apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-site
  name: nginx-site
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-site
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-site
    spec:
      containers:
        - image: knmkonexion/nginx-site:latest
          name: nginx-site
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
