apiVersion: v1
kind: Service
metadata:
  name: nginx-site
  labels:
    run: nginx-site
spec:
  type: NodePort
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
  selector:
    run: nginx-site
